export interface LocalizedName {
  ko?: string;
  en?: string;
}

export interface ManifestSite {
  name: string;
  base_url: string;
  default_lang: string;
  languages: string[];
}

export interface LobbyConfigInfo {
  enabled: boolean;
  display_mode: 'canvas' | 'grid' | 'list';
  display_order: number;
  style_params: Record<string, unknown>;
}

export interface ManifestExtension {
  id: string;
  display_name: LocalizedName;
  lobby: LobbyConfigInfo;
}

export interface Manifest {
  site: ManifestSite;
  extensions: ManifestExtension[];
}

export interface Education {
  institution: string | null;
  degree: string | null;
  field: string | null;
  start_year: number | null;
  end_year: number | null;
}

export interface CustomLink {
  label: string;
  url: string;
  icon: string | null;
}

export interface Profile {
  display_name: string;
  tagline_ko: string | null;
  tagline_en: string | null;
  avatar_url: string | null;
  bio_ko: string | null;
  bio_en: string | null;
  email: string | null;
  github_username: string | null;
  linkedin_url: string | null;
  education: Education[];
  custom_links: CustomLink[];
  updated_at: string;
}

export class ApiError extends Error {
  constructor(
    public status: number,
    message: string,
  ) {
    super(message);
    this.name = 'ApiError';
  }
}

async function apiFetch<T>(path: string): Promise<T> {
  const isStatic = import.meta.env.VITE_DATA_MODE === 'static';

  if (isStatic) {
    // Map API paths to static JSON files generated by oxipage build
    const staticPath = pathToStaticFile(path);
    const res = await fetch(staticPath);
    if (!res.ok) {
      throw new ApiError(res.status, `Static data not found: ${staticPath}`);
    }
    return res.json() as Promise<T>;
  }

  const res = await fetch(`/api/console${path}`);
  if (!res.ok) {
    throw new ApiError(res.status, `API request failed: ${res.status} ${path}`);
  }
  const json = (await res.json()) as { data: T };
  return json.data;
}

function pathToStaticFile(path: string): string {
  // Map API paths to static JSON files generated by `oxipage build`.
  // - Collection:  /blog            → /data/blog.json
  // - Detail:      /blog/<slug>     → /data/blog/<slug>.json   (per-item, with body)
  // - Detail:      /projects/<slug> → /data/projects/<slug>.json (with screenshots)
  // - Search:      /search?q=…      → /data/search-index.json (client-filtered)
  // - Other:       /<segment>       → /data/<segment>.json
  const [rawPath] = path.split('?');
  const parts = rawPath.split('/').filter(Boolean);
  if (parts.length === 0) return '/data/manifest.json';
  if (parts[0] === 'search') return '/data/search-index.json';
  if (parts.length >= 2 && (parts[0] === 'blog' || parts[0] === 'projects')) {
    return `/data/${parts[0]}/${parts[1]}.json`;
  }
  return `/data/${parts[0]}.json`;
}

export const fetchManifest = () => apiFetch<Manifest>('/lobby/manifest');
export const fetchProfile = () => apiFetch<Profile>('/profile');

// ─── blog (doc/02 §2.6) ───
export interface BlogPost {
  id: number;
  slug: string;
  title: string;
  body: string;
  lang: 'ko' | 'en';
  translation_group_id: number | null;
  tags: string[];
  published_at: string | null;
  created_at: string;
  updated_at: string;
}

// ─── projects (doc/02 §2.4) ───
export interface Project {
  id: number;
  slug: string;
  title_ko: string | null;
  title_en: string | null;
  description_ko: string | null;
  description_en: string | null;
  tech_stack: string[];
  status: 'active' | 'archived' | 'wip';
  started_at: string | null;
  ended_at: string | null;
  links: Record<string, unknown>;
  featured: boolean;
  published_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface Screenshot {
  id: number;
  project_id: number;
  url: string;
  alt_ko: string | null;
  alt_en: string | null;
  display_order: number;
  created_at: string;
}

export interface ProjectDetail extends Project {
  screenshots: Screenshot[];
}

// ─── links (doc/02 §2.11) ───
export interface LinkCard {
  id: number;
  title: string;
  url: string;
  description_ko: string | null;
  description_en: string | null;
  thumbnail_url: string | null;
  tags: string[];
  display_order: number;
  featured: boolean;
  created_at: string;
  updated_at: string;
}

// ─── search (doc/01 §1.7) ───
export interface SearchHit {
  extension_id: string;
  doc_id: string;
  title: string;
  snippet: string;
  lang: string | null;
  published_at: string | null;
}

// Cache for the per-extension collection JSON loaded once in static mode (build_spa_collection).
const collectionCache = new Map<string, Promise<unknown>>();
async function loadCollection<T>(segment: string): Promise<T[]> {
  const hit = collectionCache.get(segment);
  if (hit) return hit as Promise<T[]>;
  const p = apiFetch<T[]>(`/${segment}`);
  collectionCache.set(segment, p);
  return p;
}


export const fetchBlogPosts = () => apiFetch<BlogPost[]>('/blog');
// In static mode, /data/blog/<slug>.json is not emitted (the build emits collection-only
// /data/blog.json). Fetch the collection once and `.find()` the post by slug. In live
// mode this is just an authenticated HTTP call.
export async function fetchBlogPost(slug: string): Promise<BlogPost> {
  if (import.meta.env.VITE_DATA_MODE === 'static') {
    const posts = await loadCollection<BlogPost>('blog');
    const post = posts.find((p) => p.slug === slug);
    if (!post) throw new ApiError(404, `blog post not found: ${slug}`);
    return post;
  }
  return apiFetch<BlogPost>(`/blog/${slug}`);
}
export const fetchProjects = () => apiFetch<Project[]>('/projects');
// In static mode, /data/projects.json holds `Project[]` (no screenshots). Static-mode
// projects have no screenshots in the v2 SSG; live mode returns `ProjectDetail` with
// screenshots from the API. (Adding screenshots to the SSG is a follow-up.)
export const fetchProject = (slug: string) =>
  apiFetch<ProjectDetail>(`/projects/${slug}`);
export const fetchLinks = () => apiFetch<LinkCard[]>('/links');
// In static mode, load /data/search-index.json once and substring-filter by `q`.
// ~1k docs at ~200 bytes each = ~200KB; substring filter is sub-millisecond.
export async function searchAll(q: string, lang?: 'ko' | 'en'): Promise<SearchHit[]> {
  if (import.meta.env.VITE_DATA_MODE === 'static') {
    const docs = await loadCollection<SearchHit>('search-index');
    const needle = q.trim().toLowerCase();
    if (!needle) return docs;
    return docs.filter(
      (d) =>
        d.title.toLowerCase().includes(needle) ||
        d.snippet.toLowerCase().includes(needle),
    );
  }
  return apiFetch<SearchHit[]>(
    `/search?q=${encodeURIComponent(q)}${lang ? `&lang=${lang}` : ''}`,
  );
}
