[package]
name = "oxipage-server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "oxipage-server"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
oxipage-core = { path = "../oxipage-core" }
oxipage-ext-activity = { path = "../oxipage-ext-activity" }
oxipage-ext-blog = { path = "../oxipage-ext-blog" }
oxipage-ext-books = { path = "../oxipage-ext-books" }
oxipage-ext-links = { path = "../oxipage-ext-links" }
oxipage-ext-movies = { path = "../oxipage-ext-movies" }
oxipage-ext-novels = { path = "../oxipage-ext-novels" }
oxipage-ext-profile = { path = "../oxipage-ext-profile" }
oxipage-ext-projects = { path = "../oxipage-ext-projects" }
oxipage-ext-scraps = { path = "../oxipage-ext-scraps" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
