[package]
name = "oxipage-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "oxipage"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
directories.workspace = true
oxipage-core = { path = "../oxipage-core" }
oxipage-server = { path = "../oxipage-server" }
oxipage-admin = { path = "../oxipage-admin" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
